apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQTNGUlJJV1hKWUVMSExSNVA=
  AWS_SECRET_ACCESS_KEY: a1MxMEc2Qmd0OGVTODJPTGQrWWFCVW5qUXEvcDUvVjRJaE1mWmRQcQ==
  AWS_DEFAULT_REGION: ZXUtbm9ydGgtMQ==
